language: bash
os:
  - linux
#python:
#  - "2.7"
dist: xenial
before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple

script:
  - bash start.sh

before_install:
  - sudo apt-get update >> /dev/null
  - sudo apt-get install jq curl gettext-base sed wget >> /dev/null
  - chmod +x start.sh >> /dev/null